"use client";
import { RadioTower, Unplug } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useOperations } from "./OperationsProvider";
import { NoData, PageHeading } from "./WorkspaceParts";
export function NetworkPage() {
  const { say, state, dispatch, connected, observerLabel, observerUrl, projection, exercise, language } = useOperations();
  return <div className="hq-page"><PageHeading eyebrow={say("CONNECTIVITY", "সংযোগ")} title={say("A network that keeps going.", "যে নেটওয়ার্ক কাজ চালিয়ে যায়।")} description={say("Observe the field without becoming a dependency. Disconnecting this screen does not stop phones.", "ফিল্ডের নির্ভরতা না হয়ে পর্যবেক্ষণ করুন। এই পর্দা বিচ্ছিন্ন হলে ফোনের কাজ থামে না।")} />
    <Card><CardHeader><CardTitle>{say("Headquarters connection", "সদরদপ্তরের সংযোগ")}</CardTitle><CardDescription>{say("Read-only event stream with replay after reconnection.", "পুনঃসংযোগে রিপ্লে সহ শুধু-পাঠযোগ্য ইভেন্ট ধারা।")}</CardDescription></CardHeader><CardContent><div className="hq-connection"><RadioTower /><div><strong>{observerLabel}</strong><code>{observerUrl}</code></div><Badge variant={connected ? "secondary" : "outline"}>{connected ? say("Connected", "সংযুক্ত") : say("Not connected", "সংযুক্ত নয়")}</Badge></div><Button variant="outline" onClick={() => dispatch({ type: "TOGGLE_OBSERVER" })}><Unplug data-icon="inline-start" />{state.observerConnected ? say("Disconnect dashboard", "ড্যাশবোর্ড বিচ্ছিন্ন করুন") : say("Reconnect dashboard", "ড্যাশবোর্ড পুনঃসংযোগ")}</Button>{!state.observerConnected && <p role="status">{say("Observer disconnected. Field work continues.", "পর্যবেক্ষক বিচ্ছিন্ন। ফিল্ড কাজ চালু আছে।")}</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle>{say("Observed field sources", "পর্যবেক্ষিত ফিল্ড উৎস")}</CardTitle><CardDescription>{say("A source is listed after it publishes. Last seen does not prove current reachability or battery state.", "তথ্য পাঠানোর পর উৎস তালিকাভুক্ত হয়। সর্বশেষ উপস্থিতি বর্তমান সংযোগ বা ব্যাটারি প্রমাণ করে না।")}</CardDescription></CardHeader><CardContent>{exercise ? <p>{say("Exercise nodes A, B and C are simulated. No physical device presence is claimed.", "মহড়ার A, B ও C নোড সিমুলেটেড। বাস্তব ডিভাইসের উপস্থিতি দাবি করা হচ্ছে না।")}</p> : projection.sources.size ? <ul className="hq-source-list">{[...projection.sources].map(([id, timestamp]) => <li key={id}><RadioTower aria-hidden="true" /><strong>{id}</strong><span>{say("Last event", "সর্বশেষ তথ্য")}: {new Date(timestamp).toLocaleString(language === "bn" ? "bn-BD" : "en-GB", { timeZone: "Asia/Dhaka" })} BST</span></li>)}</ul> : <NoData title={say("No field sources seen", "কোনো ফিল্ড উৎস পাওয়া যায়নি")} detail={say("Connect an observer that is receiving device publications.", "ডিভাইসের তথ্য গ্রহণ করছে এমন পর্যবেক্ষক সংযুক্ত করুন।")} />}</CardContent></Card>
  </div>;
}
